
/* TCP Gecko Commands */

enum gecko_commands{
    COMMAND_WRITE_8 = 0x01,
    COMMAND_WRITE_16,
    COMMAND_WRITE_32,
    COMMAND_READ_MEMORY,
    COMMAND_READ_MEMORY_KERNEL,
    COMMAND_VALIDATE_ADDRESS_RANGE,
    COMMAND_UNK_7,
    COMMAND_MEMORY_DISASSEMBLE,
    COMMAND_READ_MEMORY_COMPRESSED, // TODO Remove command when done and integrate in read memory
    COMMAND_UNK_10,
    COMMAND_KERNEL_WRITE,
    COMMAND_KERNEL_READ,
    COMMAND_TAKE_SCREEN_SHOT, // TODO Finish this

    COMMAND_UPLOAD_MEMORY = 0x41,

    COMMAND_SERVER_STATUS = 0x50,
    COMMAND_GET_DATA_BUFFER_SIZE,
    COMMAND_READ_FILE,
    COMMAND_READ_DIRECTORY,
    COMMAND_REPLACE_FILE, // TODO Test this
    COMMAND_GET_CODE_HANDLER_ADDRESS,
    COMMAND_READ_THREADS,
    COMMAND_ACCOUNT_IDENTIFIER,
    COMMAND_WRITE_SCREEN, // TODO Exception DSI

    COMMAND_FOLLOW_POINTER = 0x60,

    COMMAND_REMOTE_PROCEDURE_CALL = 0x70,
    COMMAND_GET_SYMBOL,
    COMMAND_MEMORY_SEARCH_32,
    COMMAND_ADVANCED_MEMORY_SEARCH,

    COMMAND_EXECUTE_ASSEMBLY = 0x81,
    COMMAND_PAUSE_CONSOLE,
    COMMAND_RESUME_CONSOLE,
    COMMAND_IS_CONSOLE_PAUSED,

    COMMAND_SERVER_VERSION = 0x99,
    COMMAND_GET_OS_VERSION,

    COMMAND_SET_DATA_BREAKPOINT = 0xA0,

    COMMAND_SET_INSTRUCTION_BREAKPOINT = 0xA2,

    COMMAND_TOGGLE_BREAKPOINT = 0xA5,
    COMMAND_REMOVE_ALL_BREAKPOINTS,
    COMMAND_POKE_REGISTERS,
    COMMAND_GET_STACK_TRACE,

    COMMAND_GET_ENTRY_POINT_ADDRESS = 0xB1,

    COMMAND_RUN_KERNEL_COPY_SERVICE = 0xCD,

    COMMAND_IOSU_HAX_READ_FILE = 0xD0,

    COMMAND_GET_VERSION_HASH = 0xE0,
    COMMAND_PERSIST_ASSEMBLY,
    COMMAND_CLEAR_ASSEMBLY,
};

//from os_functions.h
#define PPC_DISASM_MAX_BUFFER 64

#define PPC_DISASM_DEFAULT     0x00000000  // use defaults
#define PPC_DISASM_SIMPLIFY    0x00000001  // use simplified mnemonics
#define PPC_DISASM_REG_SPACES  0x00000020  // emit spaces between registers
#define PPC_DISASM_EMIT_DISASM 0x00000040  // emit only disassembly
#define PPC_DISASM_EMIT_ADDR   0x00000080  // emit only addresses + disassembly
#define PPC_DISASM_EMIT_FUNCS  0x00000100  // emit function names before and during disassembly